// <auto-generated />
using System;
using ArenaOtbApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaOtbApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625071654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaOtbApi.Models.Arena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BoardCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtendedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeControl")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("Arenas");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.ArenaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorPlayerId");

                    b.HasIndex("ArenaId");

                    b.HasIndex("BoardId");

                    b.HasIndex("MatchId");

                    b.ToTable("ArenaEvents");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.ArenaPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<bool>("HasDevice")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMatchEndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("CurrentMatchId");

                    b.ToTable("ArenaPlayers");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("CurrentMatchId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptanceDeadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ArenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlackPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("WhitePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("BoardId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.MatchAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AcceptedByOrganizer")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchAcceptances");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OpponentConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmittedByPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SubmittedByPlayerId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Arena", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.User", "Organizer")
                        .WithMany("OrganizedArenas")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.ArenaEvent", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.ArenaPlayer", "ActorPlayer")
                        .WithMany()
                        .HasForeignKey("ActorPlayerId");

                    b.HasOne("ArenaOtbApi.Models.Arena", "Arena")
                        .WithMany("Events")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.HasOne("ArenaOtbApi.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.Navigation("ActorPlayer");

                    b.Navigation("Arena");

                    b.Navigation("Board");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.ArenaPlayer", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.Arena", "Arena")
                        .WithMany("Players")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.Match", "CurrentMatch")
                        .WithMany()
                        .HasForeignKey("CurrentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arena");

                    b.Navigation("CurrentMatch");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Board", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.Arena", "Arena")
                        .WithMany("Boards")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.Match", "CurrentMatch")
                        .WithMany()
                        .HasForeignKey("CurrentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arena");

                    b.Navigation("CurrentMatch");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Match", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.Arena", "Arena")
                        .WithMany("Matches")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.ArenaPlayer", "BlackPlayer")
                        .WithMany()
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.ArenaPlayer", "WhitePlayer")
                        .WithMany()
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("BlackPlayer");

                    b.Navigation("Board");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.MatchAcceptance", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.Match", "Match")
                        .WithMany("Acceptances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.ArenaPlayer", "Player")
                        .WithMany("MatchAcceptances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.MatchResult", b =>
                {
                    b.HasOne("ArenaOtbApi.Models.Match", "Match")
                        .WithMany("Results")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOtbApi.Models.ArenaPlayer", "SubmittedByPlayer")
                        .WithMany()
                        .HasForeignKey("SubmittedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SubmittedByPlayer");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Arena", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Events");

                    b.Navigation("Matches");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.ArenaPlayer", b =>
                {
                    b.Navigation("MatchAcceptances");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.Match", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ArenaOtbApi.Models.User", b =>
                {
                    b.Navigation("OrganizedArenas");
                });
#pragma warning restore 612, 618
        }
    }
}
